export enum GeneralErrorKey {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    FORBIDDEN = 'FORBIDDEN',
    BAD_REQUEST = 'BAD_REQUEST',
    BAD_REQUEST_VALIDATION = 'BAD_REQUEST_VALIDATION',
    ACCESS_DENIED = 'ACCESS_DENIED'
}