export enum AuthErrorKey {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    SAME_PASSWORD = 'SAME_PASSWORD',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
    USER_DEACTIVATED = 'USER_DEACTIVATED',
    ROLE_DEACTIVATED = 'ROLE_DEACTIVATED'
}