export enum UserErrorKey {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
}